### ISSUE TITLE
Error: import_libsodium_wrappers.crypto_generichash) is not a function

### ISSUE THREAD

**Issue by itsnamangoyal** [airgap-it/beacon-sdk#347]
**Describe the bug (current behavior)**
Weird error on creating new BeaconWallet instance

```import_libsodium_wrappers.crypto_generichash) is not a function```

**To Reproduce**
1. Create a new BeaconWallet instance by using ```new BeaconWallet({ name: "My DApp" })```

**Expected (correct) behavior**
Error should not be thrown.

**Screenshots and/or logs**
If applicable, add screenshots or logs to help explain your problem.
<img width="845" alt="image" src="https://user-images.githubusercontent.com/43905880/168543646-0a7bfdfd-2658-428f-8a33-ad1d72764109.png">

**Environment**

- Device: Macbook Pro M1 Chip
 - OS: MacOS 12.3.1
 - Browser: Chrome 101.0.4951.64 (Official Build) (arm64)

**Additional context**
This started happening after upgrading to v3.0.0, also tried using v3.0.0-beta2 but same error.
Reason that I tried to upgrade to latest version was that my users were reporting that they can't see qrcode for airgap wallet.
